DROP TABLE IF EXISTS training_session CASCADE;
DROP TABLE IF EXISTS personal_trainer_appointment CASCADE;
DROP TABLE IF EXISTS personal_trainer_receipt CASCADE;
DROP TABLE IF EXISTS available_time CASCADE;
DROP TABLE IF EXISTS product_employee CASCADE;
DROP TABLE IF EXISTS receipt_product CASCADE;
DROP TABLE IF EXISTS membership_type_receipt CASCADE;
DROP TABLE IF EXISTS receipt CASCADE;
DROP TABLE IF EXISTS membership CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS personal_trainer CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS membership_type CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS trainer_log CASCADE;

DROP USER IF EXISTS customer;
DROP USER IF EXISTS trainer;
DROP USER IF EXISTS admin;